test: env_variable
Signed-off-by: kobayu858 <yutaro.kobayashi@tier4.jp>

diff --git a/clang-tidy/action.yaml b/clang-tidy/action.yaml
--- a/clang-tidy/action.yaml
+++ b/clang-tidy/action.yaml
@@ -141,7 +141,7 @@ runs:
         mkdir /tmp/clang-tidy-result
         run-clang-tidy -p build/ -export-fixes /tmp/clang-tidy-result/fixes.yaml -j $(nproc) ${{ steps.get-target-files.outputs.target-files }} > /tmp/clang-tidy-result/report.log && true
         exit_code=$?
-        echo "exit-code=$exit_code"
+        echo "exit_code=$exit_code" >> $GITHUB_ENV
         echo "${{ github.event.number }}" > /tmp/clang-tidy-result/pr-id.txt
         echo "${{ github.event.pull_request.head.repo.full_name }}" > /tmp/clang-tidy-result/pr-head-repo.txt
         echo "${{ github.event.pull_request.head.ref }}" > /tmp/clang-tidy-result/pr-head-ref.txt
@@ -168,9 +168,8 @@ runs:
             /tmp/clang-tidy-result/
 
     - name: Mark the workflow as failed if clang-tidy find an error
-      if: ${{ steps.check-report-txt-existence.outputs.exists == 'true' }}
+      if: ${{ env.exit_code != '0' }}
       run: |
-        if [ -n "$(sed -r 's/\x1b\[[0-9;]*m//g' /tmp/clang-tidy-result/report.log | grep ': error:')" ]; then
-          exit 1
-        fi
+        echo "Clang-Tidy reported errors, marking the workflow as failed."
+        exit 1
       shell: bash
