test: add exit code
Signed-off-by: kobayu858 <yutaro.kobayashi@tier4.jp>

diff --git a/clang-tidy/action.yaml b/clang-tidy/action.yaml
--- a/clang-tidy/action.yaml
+++ b/clang-tidy/action.yaml
@@ -140,6 +140,8 @@ runs:
       run: |
         mkdir /tmp/clang-tidy-result
         run-clang-tidy -p build/ -export-fixes /tmp/clang-tidy-result/fixes.yaml -j $(nproc) ${{ steps.get-target-files.outputs.target-files }} > /tmp/clang-tidy-result/report.log || true
+        exit_code=$?
+        echo "exit-code=$exit_code"
         echo "${{ github.event.number }}" > /tmp/clang-tidy-result/pr-id.txt
         echo "${{ github.event.pull_request.head.repo.full_name }}" > /tmp/clang-tidy-result/pr-head-repo.txt
         echo "${{ github.event.pull_request.head.ref }}" > /tmp/clang-tidy-result/pr-head-ref.txt
@@ -168,7 +170,7 @@ runs:
     - name: Mark the workflow as failed if clang-tidy find an error
       if: ${{ steps.check-report-txt-existence.outputs.exists == 'true' }}
       run: |
-        if [ -n "$(sed -r 's/\x1b\[[0-9;]*m//g' /tmp/clang-tidy-result/report.txt | grep ': error:')" ]; then
+        if [ -n "$(sed -r 's/\x1b\[[0-9;]*m//g' /tmp/clang-tidy-result/report.log | grep ': error:')" ]; then
           exit 1
         fi
       shell: bash
